name: Go

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          cache-dependency-path: go.sum

      - name: Build
        run: go build -o ./app/ms_price_receiver/bin/ .app/ms_price_receiver/cmd/main.go

      # - name: Test
      #   run: go test -v ./...
