name: Go

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      -

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.6"
          cache-dependency-path: go.sum

      - name: Build
        run: go build -o ./bin/ ./cmd/main.go
        working-directory: ./app/ms_price_receiver

      - name: Test
        run: go test -v ./...
        working-directory: ./app/ms_price_receiver
