name: Go

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  ms_price_receiver_lint:
    name: ms_price_receiver_lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21.6"
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
          working-directory: ./app/ms_price_receiver
          args: --timeout=30m --config=./.golangci.pipeline.yaml --issues-exit-code=0

  ms_price_receiver_build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.6"
          cache-dependency-path: go.sum

      - name: ms_price_receiver_build
        run: go build -o ./bin/ ./cmd/main.go
        working-directory: ./app/ms_price_receiver

      - name: ms_price_receiver_test
        run: go test -v ./...
        working-directory: ./app/ms_price_receiver
  ms_price_saver_lint:
    name: ms_price_saver_lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21.6"
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
          working-directory: ./app/ms_price_saver
          args: --timeout=30m --config=./.golangci.pipeline.yaml --issues-exit-code=0

  ms_price_saver_build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.6"
          cache-dependency-path: go.sum

      - name: ms_price_saver_build
        run: go build -o ./bin/ ./cmd/main.go
        working-directory: ./app/ms_price_saver

      - name: ms_price_saver_test
        run: go test -v ./...
        working-directory: ./app/ms_price_saver
